[build]
    NODE_VERSION = "18.7.0"
    functions = 'netlify/functions'
    publish = 'public'
[[plugins]]
  package = "@netlify/plugin-gatsby"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200